# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_authorization_settings(object):
    def setupUi(self, Dialog_authorization_settings):
        Dialog_authorization_settings.setObjectName("Dialog_authorization_settings")
        Dialog_authorization_settings.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_authorization_settings)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_authorization_settings)
        self.widget.setGeometry(QtCore.QRect(20, 20, 361, 58))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_login = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_login.setObjectName("lineEdit_login")
        self.horizontalLayout.addWidget(self.lineEdit_login)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_password = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_2.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_authorization_settings)
        self.buttonBox.accepted.connect(Dialog_authorization_settings.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_authorization_settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_authorization_settings)

    def retranslateUi(self, Dialog_authorization_settings):
        _translate = QtCore.QCoreApplication.translate
        Dialog_authorization_settings.setWindowTitle(_translate("Dialog_authorization_settings", "Авторизация"))
        self.label.setText(_translate("Dialog_authorization_settings", "<html><head/><body><p align=\"right\">Логин:</p></body></html>"))
        self.label_2.setText(_translate("Dialog_authorization_settings", "<html><head/><body><p align=\"right\">Пароль:</p></body></html>"))
