# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog_links_food.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_links_food(object):
    def setupUi(self, Dialog_links_food):
        Dialog_links_food.setObjectName("Dialog_links_food")
        Dialog_links_food.resize(400, 149)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_links_food)
        self.buttonBox.setGeometry(QtCore.QRect(40, 100, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(Dialog_links_food)
        self.widget.setGeometry(QtCore.QRect(10, 30, 381, 58))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_links_food)
        self.buttonBox.accepted.connect(Dialog_links_food.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_links_food.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_links_food)

    def retranslateUi(self, Dialog_links_food):
        _translate = QtCore.QCoreApplication.translate
        Dialog_links_food.setWindowTitle(_translate("Dialog_links_food", "Ссылки на food"))
        self.label.setText(_translate("Dialog_links_food", "<html><head/><body><p align=\"right\">Ссылка на папку food:</p></body></html>"))
        self.label_2.setText(_translate("Dialog_links_food", "<html><head/><body><p align=\"right\">Ссылка на страницу food:</p></body></html>"))
