# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Error_post_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error_post_dialog(object):
    def setupUi(self, Error_post_dialog):
        Error_post_dialog.setObjectName("Error_post_dialog")
        Error_post_dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Error_post_dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 191, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Error_post_dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 341, 131))
        self.label_2.setObjectName("label_2")
        self.close_button = QtWidgets.QPushButton(Error_post_dialog)
        self.close_button.setGeometry(QtCore.QRect(240, 240, 113, 32))
        self.close_button.setObjectName("close_button")

        self.retranslateUi(Error_post_dialog)
        QtCore.QMetaObject.connectSlotsByName(Error_post_dialog)

    def retranslateUi(self, Error_post_dialog):
        _translate = QtCore.QCoreApplication.translate
        Error_post_dialog.setWindowTitle(_translate("Error_post_dialog", "Ошибка!"))
        self.label.setText(_translate("Error_post_dialog", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#fc0107;\">Ошибка!</span></p></body></html>"))
        self.label_2.setText(_translate("Error_post_dialog", "<html><head/><body><p>Проверьте подключение к интернету или же</p><p> настройки прокси.</p><p>Возможно, сайт edu.tatar.ru не отвечает на запрос. </p><p>В этом случае попробуйте позже. </p></body></html>"))
        self.close_button.setText(_translate("Error_post_dialog", "Ок"))
