# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Successfully_post_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Successfully_post_dialog(object):
    def setupUi(self, Successfully_post_dialog):
        Successfully_post_dialog.setObjectName("Successfully_post_dialog")
        Successfully_post_dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Successfully_post_dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 171, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Successfully_post_dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 221, 16))
        self.label_2.setObjectName("label_2")
        self.close_button = QtWidgets.QPushButton(Successfully_post_dialog)
        self.close_button.setGeometry(QtCore.QRect(240, 240, 113, 32))
        self.close_button.setObjectName("close_button")

        self.retranslateUi(Successfully_post_dialog)
        QtCore.QMetaObject.connectSlotsByName(Successfully_post_dialog)

    def retranslateUi(self, Successfully_post_dialog):
        _translate = QtCore.QCoreApplication.translate
        Successfully_post_dialog.setWindowTitle(_translate("Successfully_post_dialog", "Успешно!"))
        self.label.setText(_translate("Successfully_post_dialog", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; color:#21ff06;\">Успешно!</span></p></body></html>"))
        self.label_2.setText(_translate("Successfully_post_dialog", "Меню загружено и опубликовано"))
        self.close_button.setText(_translate("Successfully_post_dialog", "Ок"))
