# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QMainWindow(object):
    def setupUi(self, QMainWindow):
        QMainWindow.setObjectName("QMainWindow")
        QMainWindow.resize(320, 196)
        self.centralwidget = QtWidgets.QWidget(QMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_file_path = QtWidgets.QLabel(self.centralwidget)
        self.label_file_path.setGeometry(QtCore.QRect(10, 90, 300, 16))
        self.label_file_path.setObjectName("label_file_path")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 120, 191, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_send = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_send.setObjectName("pushButton_send")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_send)
        self.pushButton_close_application = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_close_application.setObjectName("pushButton_close_application")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_close_application)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 302, 69))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_unpin_file = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_unpin_file.setObjectName("pushButton_unpin_file")
        self.horizontalLayout.addWidget(self.pushButton_unpin_file)
        self.pushBatton_attach_file = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushBatton_attach_file.setObjectName("pushBatton_attach_file")
        self.horizontalLayout.addWidget(self.pushBatton_attach_file)
        QMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(QMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.Settings = QtWidgets.QMenu(self.menubar)
        self.Settings.setObjectName("Settings")
        QMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QMainWindow)
        self.statusbar.setObjectName("statusbar")
        QMainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(QMainWindow)
        self.action.setObjectName("action")
        self.actionAbout = QtWidgets.QAction(QMainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_2 = QtWidgets.QAction(QMainWindow)
        self.action_2.setObjectName("action_2")
        self.QAction_proxy_settings = QtWidgets.QAction(QMainWindow)
        self.QAction_proxy_settings.setObjectName("QAction_proxy_settings")
        self.Qaction_authorization_settings = QtWidgets.QAction(QMainWindow)
        self.Qaction_authorization_settings.setObjectName("Qaction_authorization_settings")
        self.QAction_linkfood_settings = QtWidgets.QAction(QMainWindow)
        self.QAction_linkfood_settings.setObjectName("QAction_linkfood_settings")
        self.menu.addAction(self.action)
        self.menu.addAction(self.actionAbout)
        self.Settings.addAction(self.QAction_proxy_settings)
        self.Settings.addAction(self.Qaction_authorization_settings)
        self.Settings.addAction(self.QAction_linkfood_settings)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.Settings.menuAction())

        self.retranslateUi(QMainWindow)
        QtCore.QMetaObject.connectSlotsByName(QMainWindow)

    def retranslateUi(self, QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        QMainWindow.setWindowTitle(_translate("QMainWindow", "edu_tatar_ru_food"))
        self.label_file_path.setText(_translate("QMainWindow", "Путь к файлу"))
        self.pushButton_send.setText(_translate("QMainWindow", "Отправить"))
        self.pushButton_close_application.setText(_translate("QMainWindow", "Закрыть"))
        self.pushButton_unpin_file.setText(_translate("QMainWindow", "Открепить файл"))
        self.pushBatton_attach_file.setText(_translate("QMainWindow", "Прикрепить файл"))
        self.menu.setTitle(_translate("QMainWindow", "О программе"))
        self.Settings.setTitle(_translate("QMainWindow", "Настройки"))
        self.action.setText(_translate("QMainWindow", "Лицензия"))
        self.actionAbout.setText(_translate("QMainWindow", "About"))
        self.action_2.setText(_translate("QMainWindow", "Прокси"))
        self.QAction_proxy_settings.setText(_translate("QMainWindow", "Прокси"))
        self.Qaction_authorization_settings.setText(_translate("QMainWindow", "Авторизация"))
        self.QAction_linkfood_settings.setText(_translate("QMainWindow", "Ссылки на food"))
